language: elixir

matrix:
  include:
    - elixir: 1.4.4
      otp_release: 19.3
    - elixir: 1.4.5
      otp_release: 20.0
    - elixir: 1.5.2
      otp_release: 20.1

sudo: false
env:
  - MIX_ENV=test
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix coveralls.travis
