language: elixir
otp_release:
  - 18.3
  - 19.3
elixir:
  - 1.3.4
  - 1.4.4
sudo: false
addons:
  postgresql: "9.4"
env:
  - MIX_ENV=test
before_script:
  - mix do ecto.create, ecto.migrate
script: 
  - mix coveralls.travis
