language: elixir
elixir:
  - 1.4.5
otp_release:
  - 20.0

matrix:
  include:
    - elixir: 1.3.4
      otp_release: 18.3
    - elixir: 1.4.4
      otp_release: 19.3

sudo: false
addons:
  postgresql: "9.4"
env:
  - MIX_ENV=test
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix coveralls.travis
